#!/usr/bin/env python3
import json
from pathlib import Path

# Safe patch: run this in the same folder as your existing players.json.
# It validates the existing 200-card structure before making any changes.
PATH = Path("players.json")

# name: (draft year, overall pick, original drafting team)
UPDATES = {
    "Tyrese Haliburton": (2020, 12, "Sacramento Kings"),
    "Cooper Flagg": (2025, 1, "Dallas Mavericks"),
    "Alperen Sengun": (2021, 16, "Houston Rockets"),
    "Chet Holmgren": (2022, 2, "Oklahoma City Thunder"),
    "Amen Thompson": (2023, 4, "Houston Rockets"),
    "Josh Giddey": (2021, 6, "Oklahoma City Thunder"),
    "Trey Murphy III": (2021, 17, "Memphis Grizzlies"),
    "Evan Mobley": (2021, 3, "Cleveland Cavaliers"),
    "Lauri Markkanen": (2017, 7, "Minnesota Timberwolves"),
    "Deni Avdija": (2020, 9, "Washington Wizards"),
    "Jalen Williams": (2022, 12, "Oklahoma City Thunder"),
    "Brandon Miller": (2023, 2, "Charlotte Hornets"),
    "Walker Kessler": (2022, 22, "Memphis Grizzlies"),
    "Derrick White": (2017, 29, "San Antonio Spurs"),
    "Kon Knueppel": (2025, 4, "Charlotte Hornets"),
    "Jaylen Brown": (2016, 3, "Boston Celtics"),
    "Jalen Duren": (2022, 13, "Charlotte Hornets"),
    "Keyonte George": (2023, 16, "Utah Jazz"),
    "Nickeil Alexander-Walker": (2019, 17, "Brooklyn Nets"),
    "Desmond Bane": (2020, 30, "Boston Celtics"),
    "Onyeka Okongwu": (2020, 6, "Atlanta Hawks"),
    "Donovan Clingan": (2024, 7, "Portland Trail Blazers"),
    "Tyler Herro": (2019, 13, "Miami Heat"),
    "Matas Buzelis": (2024, 11, "Chicago Bulls"),
    "Dyson Daniels": (2022, 8, "New Orleans Pelicans"),
    "Franz Wagner": (2021, 8, "Orlando Magic"),
    "Pascal Siakam": (2016, 27, "Toronto Raptors"),
    "OG Anunoby": (2017, 23, "Toronto Raptors"),
    "Dejounte Murray": (2016, 29, "San Antonio Spurs"),
    "Ryan Rollins": (2022, 44, "Golden State Warriors"),
    "Julius Randle": (2014, 7, "Los Angeles Lakers"),
    "Michael Porter Jr.": (2018, 14, "Denver Nuggets"),
    "Kel’el Ware": (2024, 15, "Miami Heat"),
    "Alex Sarr": (2024, 2, "Washington Wizards"),
    "Stephon Castle": (2024, 4, "San Antonio Spurs"),
    "Zach Edey": (2024, 9, "Memphis Grizzlies"),
    "Ivica Zubac": (2016, 32, "Los Angeles Lakers"),
    "De’Aaron Fox": (2017, 5, "Sacramento Kings"),
    "Mikal Bridges": (2018, 10, "Philadelphia 76ers"),
    "Ja Morant": (2019, 2, "Memphis Grizzlies"),
    "Jaden McDaniels": (2020, 28, "Los Angeles Lakers"),
    "Rudy Gobert": (2013, 27, "Denver Nuggets"),
    "VJ Edgecombe": (2025, 3, "Philadelphia 76ers"),
    "Immanuel Quickley": (2020, 25, "Oklahoma City Thunder"),
    "Coby White": (2019, 7, "Chicago Bulls"),
    "Brandon Ingram": (2016, 2, "Los Angeles Lakers"),
    "Paul George": (2010, 10, "Indiana Pacers"),
    "Dylan Harper": (2025, 2, "San Antonio Spurs"),
    "Zion Williamson": (2019, 1, "New Orleans Pelicans"),
    "Jarrett Allen": (2017, 22, "Brooklyn Nets"),
    "Payton Pritchard": (2020, 26, "Boston Celtics"),
    "Jalen Suggs": (2021, 5, "Orlando Magic"),
    "Ausar Thompson": (2023, 5, "Detroit Pistons"),
    "Josh Hart": (2017, 30, "Utah Jazz"),
    "Norman Powell": (2015, 46, "Milwaukee Bucks"),
    "Ty Jerome": (2019, 24, "Philadelphia 76ers"),
    "Derik Queen": (2025, 13, "Atlanta Hawks"),
    "Jabari Smith Jr.": (2022, 3, "Houston Rockets"),
    "Myles Turner": (2015, 11, "Indiana Pacers"),
    "Andrew Wiggins": (2014, 1, "Cleveland Cavaliers"),
    "Nic Claxton": (2019, 31, "Brooklyn Nets"),
    "Isaiah Hartenstein": (2017, 43, "Houston Rockets"),
    "Day’Ron Sharpe": (2021, 29, "Phoenix Suns"),
    "Kevin Porter Jr.": (2019, 30, "Milwaukee Bucks"),
    "Ayo Dosunmu": (2021, 38, "Chicago Bulls"),
    "Cedric Coward": (2025, 11, "Portland Trail Blazers"),
    "Kyshawn George": (2024, 24, "New York Knicks"),
    "CJ McCollum": (2013, 10, "Portland Trail Blazers"),
    "Miles Bridges": (2018, 12, "Los Angeles Clippers"),
    "John Collins": (2017, 19, "Atlanta Hawks"),
    "Ajay Mitchell": (2024, 38, "New York Knicks"),
    "Zach LaVine": (2014, 13, "Minnesota Timberwolves"),
    "Keegan Murray": (2022, 4, "Sacramento Kings"),
    "Reed Sheppard": (2024, 3, "Houston Rockets"),
    "Neemias Queta": (2021, 39, "Sacramento Kings"),
    "Toumani Camara": (2023, 52, "Phoenix Suns"),
    "Peyton Watson": (2022, 30, "Denver Nuggets"),
    "Collin Murray-Boyles": (2025, 9, "Toronto Raptors"),
    "Jakob Poeltl": (2016, 9, "Toronto Raptors"),
    "Jalen Green": (2021, 2, "Houston Rockets"),
    "Mark Williams": (2022, 15, "Charlotte Hornets"),
    "Cason Wallace": (2023, 10, "Dallas Mavericks"),
    "RJ Barrett": (2019, 3, "New York Knicks"),
    "Brandin Podziemski": (2023, 19, "Golden State Warriors"),
    "Jusuf Nurkić": (2014, 16, "Chicago Bulls"),
    "Maxime Raynaud": (2025, 42, "Sacramento Kings"),
    "Kristaps Porziņģis": (2015, 4, "New York Knicks"),
    "Anthony Black": (2023, 6, "Orlando Magic"),
    "Jeremiah Fears": (2025, 7, "New Orleans Pelicans"),
    "Sandro Mamukelashvili": (2021, 54, "Indiana Pacers"),
    "Davion Mitchell": (2021, 9, "Sacramento Kings"),
    "Egor Dëmin": (2025, 8, "Brooklyn Nets"),
    "Andrew Nembhard": (2022, 31, "Indiana Pacers"),
    "P.J. Washington": (2019, 12, "Charlotte Hornets"),
    "Quentin Grimes": (2021, 25, "Los Angeles Clippers"),
    "Saddiq Bey": (2020, 19, "Brooklyn Nets"),
    "Jaime Jaquez Jr.": (2023, 18, "Miami Heat"),
    "Tari Eason": (2022, 17, "Houston Rockets"),
    "DeMar DeRozan": (2009, 9, "Toronto Raptors"),
    "Christian Braun": (2022, 21, "Denver Nuggets"),
    "Ace Bailey": (2025, 5, "Utah Jazz"),
    "Aaron Gordon": (2014, 4, "Orlando Magic"),
    "Devin Vassell": (2020, 11, "San Antonio Spurs"),
    "Cameron Johnson": (2019, 11, "Minnesota Timberwolves"),
    "Bennedict Mathurin": (2022, 6, "Indiana Pacers"),
    "Jrue Holiday": (2009, 17, "Philadelphia 76ers"),
    "Grayson Allen": (2018, 21, "Utah Jazz"),
    "Karl Malone": (1985, 13, "Utah Jazz"),
    "Nikola Jokić": (2014, 41, "Denver Nuggets"),
    "Victor Wembanyama": (2023, 1, "San Antonio Spurs"),
    "Shai Gilgeous-Alexander": (2018, 11, "Charlotte Hornets"),
    "Luka Dončić": (2018, 3, "Atlanta Hawks"),
    "Cade Cunningham": (2021, 1, "Detroit Pistons"),
    "Jayson Tatum": (2017, 3, "Boston Celtics"),
    "Giannis Antetokounmpo": (2013, 15, "Milwaukee Bucks"),
    "Jalen Johnson": (2021, 20, "Atlanta Hawks"),
    "Anthony Edwards": (2020, 1, "Minnesota Timberwolves"),
    "Tyrese Maxey": (2020, 21, "Philadelphia 76ers"),
    "Scottie Barnes": (2021, 4, "Toronto Raptors"),
    "Donovan Mitchell": (2017, 13, "Denver Nuggets"),
    "Kevin Durant": (2007, 2, "Seattle SuperSonics"),
    "Stephen Curry": (2009, 7, "Golden State Warriors"),
    "Karl-Anthony Towns": (2015, 1, "Minnesota Timberwolves"),
    "Trae Young": (2018, 5, "Dallas Mavericks"),
    "James Harden": (2009, 3, "Oklahoma City Thunder"),
    "LaMelo Ball": (2020, 3, "Charlotte Hornets"),
    "Jamal Murray": (2016, 7, "Denver Nuggets"),
    "Anthony Davis": (2012, 1, "New Orleans Hornets"),
    "Devin Booker": (2015, 13, "Phoenix Suns"),
    "Jalen Brunson": (2018, 33, "Dallas Mavericks"),
    "Domantas Sabonis": (2016, 11, "Orlando Magic"),
    "Kawhi Leonard": (2011, 15, "Indiana Pacers"),
    "Bam Adebayo": (2017, 14, "Miami Heat"),
    "Jaren Jackson Jr.": (2018, 4, "Memphis Grizzlies"),
    "Darius Garland": (2019, 5, "Cleveland Cavaliers"),
    "Kyrie Irving": (2011, 1, "Cleveland Cavaliers"),
    "Paolo Banchero": (2022, 1, "Orlando Magic"),
    "LeBron James": (2003, 1, "Cleveland Cavaliers"),
    "Cameron Boozer": (2026, 3, "Memphis Grizzlies"),
    "Joel Embiid": (2014, 3, "Philadelphia 76ers"),
    "Damian Lillard": (2012, 6, "Portland Trail Blazers"),
    "AJ Dybantsa": (2026, 1, "Washington Wizards"),
    "Caleb Wilson": (2026, 4, "Chicago Bulls"),
    "Darryn Peterson": (2026, 2, "Utah Jazz"),
    "Darius Acuff Jr.": (2026, 7, "Sacramento Kings"),
    "Yaxel Lendeborg": (2026, 11, "Golden State Warriors"),
    "Mikel Brown Jr.": (2026, 6, "Brooklyn Nets"),
    "Michael Jordan": (1984, 3, "Chicago Bulls"),
    "Jordan Clarkson": (2014, 46, "Washington Wizards"),
    "Kareem Abdul-Jabbar": (1969, 1, "Milwaukee Bucks"),
    "Bill Russell": (1956, 2, "St. Louis Hawks"),
    "Wilt Chamberlain": (1959, 1, "Philadelphia Warriors"),
    "Magic Johnson": (1979, 1, "Los Angeles Lakers"),
    "Larry Bird": (1978, 6, "Boston Celtics"),
    "Tim Duncan": (1997, 1, "San Antonio Spurs"),
    "Shaquille O'Neal": (1992, 1, "Orlando Magic"),
    "Kobe Bryant": (1996, 13, "Charlotte Hornets"),
    "Hakeem Olajuwon": (1984, 1, "Houston Rockets"),
    "Oscar Robertson": (1960, 1, "Cincinnati Royals"),
    "Jerry West": (1960, 2, "Minneapolis Lakers"),
    "Landry Shamet": (2018, 26, "Philadelphia 76ers"),
    "Julius Erving": (1972, 12, "Milwaukee Bucks"),
    "Moses Malone": (1974, 3, "Utah Stars"),
    "John Stockton": (1984, 16, "Utah Jazz"),
    "Charles Barkley": (1984, 5, "Philadelphia 76ers"),
    "David Robinson": (1987, 1, "San Antonio Spurs"),
    "Kevin Garnett": (1995, 5, "Minnesota Timberwolves"),
    "Dirk Nowitzki": (1998, 9, "Milwaukee Bucks"),
    "Jared McCain": (2024, 16, "Philadelphia 76ers"),
    "Elgin Baylor": (1958, 1, "Minneapolis Lakers"),
    "Bob Pettit": (1954, 2, "Milwaukee Hawks"),
    "Rick Barry": (1965, 2, "San Francisco Warriors"),
    "Isiah Thomas": (1981, 2, "Detroit Pistons"),
    "John Havlicek": (1962, 7, "Boston Celtics"),
    "Scottie Pippen": (1987, 5, "Seattle SuperSonics"),
    "Dwyane Wade": (2003, 5, "Miami Heat"),
    "Chris Paul": (2005, 4, "New Orleans Hornets"),
    "Steve Nash": (1996, 15, "Phoenix Suns"),
    "Allen Iverson": (1996, 1, "Philadelphia 76ers"),
    "Patrick Ewing": (1985, 1, "New York Knicks"),
    "Clyde Drexler": (1983, 14, "Portland Trail Blazers"),
    "Jason Kidd": (1994, 2, "Dallas Mavericks"),
    "Jaylin Williams": (2022, 34, "Oklahoma City Thunder"),
    "George Gervin": (1972, 40, "Phoenix Suns"),
    "Russell Westbrook": (2008, 4, "Seattle SuperSonics"),
    "Harrison Barnes": (2012, 7, "Golden State Warriors"),
    "Tobias Harris": (2011, 19, "Charlotte Bobcats"),
    "Kevin McHale": (1980, 3, "Boston Celtics"),
    "Bill Walton": (1974, 1, "Portland Trail Blazers"),
    "Walt Frazier": (1967, 5, "New York Knicks"),
    "Gary Payton": (1990, 2, "Seattle SuperSonics"),
    "Reggie Miller": (1987, 11, "Indiana Pacers"),
    "Dominique Wilkins": (1982, 3, "Utah Jazz"),
}

UNDRAFTED = {
    "Austin Reaves", "Naz Reid", "Fred VanVleet",
    "Collin Gillespie", "Jose Alvarado", "Alex Caruso",
    "Julian Champagnie"
}

data = json.loads(PATH.read_text(encoding="utf-8"))
assert len(data) == 200
assert len({p["id"] for p in data}) == 200
assert len({p["name"] for p in data}) == 200

by_name = {p["name"]: p for p in data}
missing = [n for n in list(UPDATES) + list(UNDRAFTED) if n not in by_name]
if missing:
    raise SystemExit("Player names not found: " + ", ".join(missing))

# Do not modify a dataset whose rank structure isn't the known-good structure.
assert sorted(p["rank"] for p in data if p.get("category") == "Current Players") == list(range(1, 160))
assert sorted(p["rank"] for p in data if p.get("category") == "Classic Players") == list(range(1, 42))

for name, (year, pick, team) in UPDATES.items():
    p = by_name[name]
    p["draftYear"], p["draftPick"], p["draftedBy"] = year, pick, team

for name in UNDRAFTED:
    p = by_name[name]
    p["draftYear"], p["draftPick"], p["draftedBy"] = None, None, "Undrafted"

# Atomic write: players.json is changed only after every check passes.
tmp = PATH.with_suffix(".json.tmp")
tmp.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
tmp.replace(PATH)

print("Draft data patch applied successfully.")
print("200 players; 159 Current Players ranks; 41 Classic Players ranks.")
print(f"Updated {len(UPDATES)} drafted records and {len(UNDRAFTED)} undrafted records.")
